version: "3"
services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app

  redis:
    image: redis
    command: redis-server --appendonly yes

  worker:
    build: .
    entrypoint: celery
    command: -A app.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis

volumes:
  redis: {}